# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "development", "feature/*", "release/qa" ]
  pull_request:
    branches: [ "main", "development", "feature/*", "release/qa" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # quiero que cualquier pr a release/qa venga especificamente de la rama feature/* y no de main o development
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release/qa' && !startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying!"
