name: Restrict Direct Pushes

on:
  push:
    branches:
      - "main"
      - "development"
      - "release/qa"
      
jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Print GitHub Event
      run: |
        echo "GitHub Event:"
        echo "${{ toJson(github.event) }}"
        echo "Commit Messages:"
        for commit in "${{ github.event.commits }}"; do
          echo "$commit"
        done
    - name: Block Direct Push
      run: |
        # Obtener todos los mensajes de los commits
        commit_messages="${{ github.event.commits[*].message }}"
        echo "Commit messages: $commit_messages"
        
        # Comprobar si algún commit es un "Merge pull request"
        if [[ "$commit_messages" == *"Merge pull request"* ]]; then
          echo "Merge detected, no direct push blocking needed."
        else
          echo "Error: No se permite hacer push directo a main, development o release/qa."
          exit 1
        fi
