name: Restrict Direct Pushes

on:
  push:
    branches:
      - "main"
      - "development"
      - "release/qa"
  
  pull_request:
    branches:
      - "main"
      - "development"
      - "release/qa"
      
jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Block Direct Push
      run: |
        echo ${{ github.event.action }}
        echo ${{ github.event.commits }}
        echo ${{ github.event.compare }}
        echo ${{ github.event.before }}
        echo ${{ github.event.after }}
        echo ${{ github.event.head_commit }}
        echo ${{ github.event.repository }}
        echo ${{ github.event.sender }}
        echo ${{ github.event_name }}
        echo ${{ github.ref }}
        echo ${{ github.ref_type }}
        echo ${{ github.head_ref }}
        echo ${{ github.base_ref }}
        echo ${{ github.event.pull_request.head.ref }}
        echo ${{ github.event.pull_request.base.ref }}
        echo ${{ github.event.pull_request.head.repo.full_name }}
        echo ${{ github.event.pull_request.head.repo.owner.login }}