name: Restrict Direct Pushes

on:
  push:
    branches:
      - "main"
      - "development"
      - "release/qa"
      
jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Print GitHub Event
      run: |
        echo "GitHub Event:"
        echo "${{ toJson(github.event) }}"
    - name: Block Direct Push
      run: |
        if [[ "${{ github.event_name }}" == "push" && ! "${{ github.event.head_commit.message }}" == *"Merge pull request"* ]]; then
          echo "Error: No se permite hacer push directo a main, development o release/qa."
          exit 1
        fi
